# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: GNU の青色申告
tagline: やよいの青色申告から GnuCash へ
email: takuya0301+gnucash@gmail.com
description: 個人事業主のエンジニアが無料の会計ソフトウェア GnuCash で青色申告する顛末を書いていくブログです。やよいの青色申告と GnuCash を並行運用しながら試行錯誤していきます。
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gnucash.jp" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap

# Outputting
permalink: /:title.html

# Markdown Processors
kramdown:
  auto_ids: false
